image:
    file: .gitpod.dockerfile

vscode:
    extensions:
        - eamodio.gitlens
        - github.vscode-pull-request-github
        - ms-azuretools.vscode-docker
        - ms-vscode.cmake-tools

tasks:
    - init: git submodule update --init --recursive

ports:
    - port: 6080
        onOpen: open-preview
    - port: 5900
        onOpen: ignore
