#
# This file is part of the Visual Computing Library (VCL) release under the
# MIT license.
#
# Copyright (c) 2014 Basil Fierz
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
version: '{build}'

image:
  - Visual Studio 2022

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  MSVC_DEFAULT_OPTIONS: ON

  matrix:
    - tool_set: 'v140'
      vec_type: 'AVX'
      cpp_std: '14'

    - tool_set: 'v141'
      vec_type: 'AVX'
      cpp_std: '14'

    - tool_set: 'v142'
      vec_type: 'AVX'
      cpp_std: '17'

    - tool_set: 'v143'
      vec_type: 'SSE 2'
      cpp_std: '20'
    - tool_set: 'v143'
      vec_type: 'SSE 3'
      cpp_std: '20'
    - tool_set: 'v143'
      vec_type: 'SSE 4.1'
      cpp_std: '20'
    - tool_set: 'v143'
      vec_type: 'SSE 4.2'
      cpp_std: '20'
    - tool_set: 'v143'
      vec_type: 'AVX'
      cpp_std: '20'

    - tool_set: 'ClangCL'
      vec_type: 'AVX'
      cpp_std: '14'

branches:
  only:
    - master

init:
  - cmd: msbuild /version

clone_folder: C:\projects\vcl

install:
  # Update all the submodules of the project
  - cmd: git submodule update --init --recursive

before_build:
  # Disable vcpkg integration as it interferes with clang-cl and cmake
  - cmd: vcpkg integrate remove
  - cmd: cd C:\projects\vcl
  - cmd: md build
  - cmd: cd build
  - cmd: 'cmake -G "Visual Studio 17 2022" -A "%platform%" -T "%tool_set%,host=x64" -DVCL_CXX_STANDARD:STRING=%cpp_std% -DVCL_CODE_COVERAGE:BOOL=off -DVCL_ENABLE_CORE_GUIDELINE_CHECKER:BOOL=off -DVCL_BUILD_BENCHMARKS:BOOL=off -DVCL_BUILD_TESTS:BOOL=on -DVCL_BUILD_TOOLS:BOOL=off -DVCL_BUILD_EXAMPLES:BOOL=off -DVCL_VECTORIZE:STRING="%vec_type%" ..'

build_script:
  - cmd: cd C:\projects\vcl
  - cmd: cmake --build build --config %configuration% --target vcl.components.test
  - cmd: cmake --build build --config %configuration% --target vcl.core.test
  - cmd: cmake --build build --config %configuration% --target vcl.geometry.test
  - cmd: if "%configuration%"=="Debug" cmake --build build --config %configuration% --target vcl.math.test

test_script:
  - cmd: cd C:\projects\vcl\build\src\tests
  - cmd: ctest --no-compress-output -T Test || verify > NUL

on_finish:
  # Tap in for debug CMake problems
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
