# Control OpenCL support
SET(VCL_OPENCL_SUPPORT CACHE BOOL "Enable OpenCL support")
IF(VCL_OPENCL_SUPPORT)
	FIND_PACKAGE(OpenCL)
	IF(OPENCL_FOUND)
		ADD_DEFINITIONS(-DVCL_OPENCL_SUPPORT)
	ENDIF()
ENDIF()
